# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NISkzQi4wxm9IV1Ja2_liX3Z5SEFOdi5
"""

import streamlit as st
import openai

# Set your OpenAI API key
api_key = "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"
openai.api_key = api_key

# Define a function to interact with the chatbot
def chat_with_bot(user_message, conversation=[]):
    conversation.append({"role": "user", "content": user_message})
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=conversation
    )
    bot_message = response['choices'][0]['message']['content']
    conversation.append({"role": "assistant", "content": bot_message})
    return bot_message, conversation

# Define a function to start a new conversation
def start_new_conversation():
    conversation = []
    # You can set a system message to provide context if needed
    system_message = "You are chatting with a wealth advisor chatbot."
    conversation.append({"role": "system", "content": system_message})
    return conversation

# Streamlit UI
st.title("Wealth Advisor Chatbot")

user_input = st.text_input("You:", key="user_input")

if st.button("Send"):
    if not user_input:
        st.warning("Please enter a message.")
    else:
        # Initialize or continue the conversation
        if "conversation" not in st.session_state:
            st.session_state.conversation = start_new_conversation()

        bot_response, st.session_state.conversation = chat_with_bot(user_input, st.session_state.conversation)
        st.write("Chatbot: " + bot_response)  # Use st.write() instead of st.text()

if st.button("Start New Conversation"):
    st.session_state.conversation = start_new_conversation()
    st.text("Chatbot:", "You are now chatting with the wealth advisor chatbot.")

